// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	sometype "go_gen/proto3cloneV2/example/sometype"
	example2 "go_gen/proto3cloneV2/example2"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求Debug命令
// |RequestServiceDebugCmd
type RequestServiceDebugCmd struct {
	Cmd                  string                              `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Commanders           [][]byte                            `protobuf:"bytes,2,rep,name=commanders,proto3" json:"commanders,omitempty"`
	Binary               []*sometype.ApplesServerin          `protobuf:"bytes,3,rep,name=binary,proto3" json:"binary,omitempty"`
	SandBox              []*LocalWay                         `protobuf:"bytes,4,rep,name=sandBox,proto3" json:"sandBox,omitempty"`
	Apple                *sometype.ApplesServerin            `protobuf:"bytes,5,opt,name=apple,proto3" json:"apple,omitempty"`
	Ll                   *LocalWay                           `protobuf:"bytes,6,opt,name=ll,proto3" json:"ll,omitempty"`
	Tem                  map[string]int32                    `protobuf:"bytes,7,rep,name=tem,proto3" json:"tem,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Tem2                 map[string]*LocalWay                `protobuf:"bytes,8,rep,name=tem2,proto3" json:"tem2,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AddrEntry            map[string]*sometype.ApplesServerin `protobuf:"bytes,9,rep,name=addrEntry,proto3" json:"addrEntry,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Hero                 *example2.Hero                      `protobuf:"bytes,10,opt,name=hero,proto3" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *RequestServiceDebugCmd) Reset()         { *m = RequestServiceDebugCmd{} }
func (m *RequestServiceDebugCmd) String() string { return proto.CompactTextString(m) }
func (*RequestServiceDebugCmd) ProtoMessage()    {}
func (*RequestServiceDebugCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *RequestServiceDebugCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestServiceDebugCmd.Unmarshal(m, b)
}
func (m *RequestServiceDebugCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestServiceDebugCmd.Marshal(b, m, deterministic)
}
func (m *RequestServiceDebugCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestServiceDebugCmd.Merge(m, src)
}
func (m *RequestServiceDebugCmd) XXX_Size() int {
	return xxx_messageInfo_RequestServiceDebugCmd.Size(m)
}
func (m *RequestServiceDebugCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestServiceDebugCmd.DiscardUnknown(m)
}

var xxx_messageInfo_RequestServiceDebugCmd proto.InternalMessageInfo

func (m *RequestServiceDebugCmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *RequestServiceDebugCmd) GetCommanders() [][]byte {
	if m != nil {
		return m.Commanders
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetBinary() []*sometype.ApplesServerin {
	if m != nil {
		return m.Binary
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetSandBox() []*LocalWay {
	if m != nil {
		return m.SandBox
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetApple() *sometype.ApplesServerin {
	if m != nil {
		return m.Apple
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetLl() *LocalWay {
	if m != nil {
		return m.Ll
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetTem() map[string]int32 {
	if m != nil {
		return m.Tem
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetTem2() map[string]*LocalWay {
	if m != nil {
		return m.Tem2
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetAddrEntry() map[string]*sometype.ApplesServerin {
	if m != nil {
		return m.AddrEntry
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetHero() *example2.Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

type LocalWay struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalWay) Reset()         { *m = LocalWay{} }
func (m *LocalWay) String() string { return proto.CompactTextString(m) }
func (*LocalWay) ProtoMessage()    {}
func (*LocalWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *LocalWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalWay.Unmarshal(m, b)
}
func (m *LocalWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalWay.Marshal(b, m, deterministic)
}
func (m *LocalWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalWay.Merge(m, src)
}
func (m *LocalWay) XXX_Size() int {
	return xxx_messageInfo_LocalWay.Size(m)
}
func (m *LocalWay) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalWay.DiscardUnknown(m)
}

var xxx_messageInfo_LocalWay proto.InternalMessageInfo

func (m *LocalWay) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestServiceDebugCmd)(nil), "example.RequestServiceDebugCmd")
	proto.RegisterMapType((map[string]*sometype.ApplesServerin)(nil), "example.RequestServiceDebugCmd.AddrEntryEntry")
	proto.RegisterMapType((map[string]*LocalWay)(nil), "example.RequestServiceDebugCmd.Tem2Entry")
	proto.RegisterMapType((map[string]int32)(nil), "example.RequestServiceDebugCmd.TemEntry")
	proto.RegisterType((*LocalWay)(nil), "example.localWay")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0xcb, 0xd3, 0x40,
	0x10, 0x80, 0x49, 0xd2, 0xb4, 0xcd, 0xa8, 0x41, 0x17, 0x91, 0x25, 0x07, 0x89, 0xbd, 0x18, 0x11,
	0x16, 0x89, 0x20, 0x52, 0xf0, 0xe0, 0x17, 0x88, 0x78, 0x5a, 0x45, 0xcf, 0xdb, 0x64, 0xd0, 0xd0,
	0xdd, 0x6c, 0xdc, 0xa4, 0xa5, 0xf9, 0x81, 0xfe, 0x2f, 0xc9, 0xe6, 0xe3, 0x6d, 0x21, 0xf4, 0x7d,
	0x6f, 0x99, 0x9d, 0x79, 0x9e, 0xc9, 0xec, 0x2c, 0x3c, 0xc0, 0x93, 0x50, 0x95, 0x44, 0x56, 0x19,
	0xdd, 0x68, 0xb2, 0x1a, 0xc2, 0x28, 0xac, 0xb5, 0xc2, 0xa6, 0xad, 0x86, 0x44, 0x14, 0x0e, 0x89,
	0xb4, 0x8f, 0x37, 0xff, 0x7c, 0x78, 0xc2, 0xf1, 0xef, 0x01, 0xeb, 0xe6, 0x3b, 0x9a, 0x63, 0x91,
	0xe1, 0x27, 0xdc, 0x1d, 0x7e, 0x7f, 0x54, 0x39, 0x79, 0x08, 0x5e, 0xa6, 0x72, 0xea, 0xc4, 0x4e,
	0x12, 0xf0, 0xee, 0x93, 0x3c, 0x05, 0xc8, 0xb4, 0x52, 0xa2, 0xcc, 0xd1, 0xd4, 0xd4, 0x8d, 0xbd,
	0xe4, 0x3e, 0x3f, 0x3b, 0x21, 0xaf, 0x60, 0xb9, 0x2b, 0x4a, 0x61, 0x5a, 0xea, 0xc5, 0x5e, 0x72,
	0x2f, 0xa5, 0x6c, 0xea, 0x2e, 0xaa, 0x4a, 0x62, 0xdd, 0xb5, 0x40, 0x53, 0x94, 0x7c, 0xa8, 0x23,
	0x2f, 0x61, 0x55, 0x8b, 0x32, 0xff, 0xa0, 0x4f, 0x74, 0x61, 0x91, 0x47, 0x6c, 0x1c, 0x44, 0xea,
	0x4c, 0xc8, 0x5f, 0xa2, 0xe5, 0x63, 0x05, 0x61, 0xe0, 0x5b, 0x0d, 0xf5, 0x63, 0xe7, 0xaa, 0xbd,
	0x2f, 0x23, 0xcf, 0xc0, 0x95, 0x92, 0x2e, 0x6d, 0xf1, 0x8c, 0xd7, 0x95, 0x92, 0x6c, 0xc1, 0x6b,
	0x50, 0xd1, 0x95, 0xed, 0x9d, 0x4c, 0x35, 0xf3, 0x37, 0xc2, 0x7e, 0xa0, 0xfa, 0x5c, 0x36, 0xa6,
	0xe5, 0x1d, 0x44, 0xde, 0xc1, 0xa2, 0x41, 0x95, 0xd2, 0xb5, 0x85, 0x5f, 0xdc, 0x01, 0x4e, 0x7b,
	0xda, 0x62, 0xe4, 0x1b, 0x04, 0x22, 0xcf, 0x8d, 0x3d, 0xa2, 0x81, 0x75, 0xb0, 0xdb, 0x1c, 0xef,
	0x47, 0xa0, 0x17, 0xdd, 0x08, 0xc8, 0x06, 0x16, 0x7f, 0xd0, 0x68, 0x0a, 0x76, 0xda, 0x90, 0x4d,
	0x6b, 0xfe, 0x82, 0x46, 0x73, 0x9b, 0x8b, 0xde, 0xc0, 0x7a, 0x9c, 0xa0, 0x5b, 0xee, 0x1e, 0xdb,
	0x71, 0xb9, 0x7b, 0x6c, 0xc9, 0x63, 0xf0, 0x8f, 0x42, 0x1e, 0x90, 0xba, 0xb1, 0x93, 0xf8, 0xbc,
	0x0f, 0xb6, 0xee, 0x5b, 0x27, 0xfa, 0x0a, 0xc1, 0xf4, 0xf3, 0x33, 0xe0, 0xf3, 0x73, 0x70, 0xf6,
	0xa6, 0xcf, 0x5c, 0x3f, 0x21, 0xbc, 0x1c, 0x62, 0x46, 0xc8, 0x2e, 0x85, 0x57, 0xf6, 0x3c, 0x79,
	0x37, 0x11, 0xac, 0xc7, 0x76, 0x24, 0x04, 0xb7, 0xe8, 0xdf, 0xad, 0xcf, 0xdd, 0x22, 0xdf, 0x2d,
	0xed, 0x53, 0x7f, 0xfd, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xab, 0xb1, 0x1d, 0x24, 0x03, 0x00,
	0x00,
}
