// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求Debug命令
type RequestServiceDebugCmd struct {
	Cmd                  string                     `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Param                []byte                     `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	Groups               []int32                    `protobuf:"varint,3,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	Unit                 []string                   `protobuf:"bytes,4,rep,name=unit,proto3" json:"unit,omitempty"`
	Beasts               []int32                    `protobuf:"varint,5,rep,packed,name=beasts,proto3" json:"beasts,omitempty"`
	Commanders           [][]byte                   `protobuf:"bytes,6,rep,name=commanders,proto3" json:"commanders,omitempty"`
	Apple                *ApplesServerin            `protobuf:"bytes,7,opt,name=apple,proto3" json:"apple,omitempty"`
	Tem                  map[string]int32           `protobuf:"bytes,8,rep,name=tem,proto3" json:"tem,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Addr                 map[string]int32           `protobuf:"bytes,9,rep,name=addr,proto3" json:"addr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AddrEntry            map[string]*ApplesServerin `protobuf:"bytes,10,rep,name=addrEntry,proto3" json:"addrEntry,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AddrEntry2           map[string]*ApplesServerin `protobuf:"bytes,11,rep,name=addrEntry2,proto3" json:"addrEntry2,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RequestServiceDebugCmd) Reset()         { *m = RequestServiceDebugCmd{} }
func (m *RequestServiceDebugCmd) String() string { return proto.CompactTextString(m) }
func (*RequestServiceDebugCmd) ProtoMessage()    {}
func (*RequestServiceDebugCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *RequestServiceDebugCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestServiceDebugCmd.Unmarshal(m, b)
}
func (m *RequestServiceDebugCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestServiceDebugCmd.Marshal(b, m, deterministic)
}
func (m *RequestServiceDebugCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestServiceDebugCmd.Merge(m, src)
}
func (m *RequestServiceDebugCmd) XXX_Size() int {
	return xxx_messageInfo_RequestServiceDebugCmd.Size(m)
}
func (m *RequestServiceDebugCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestServiceDebugCmd.DiscardUnknown(m)
}

var xxx_messageInfo_RequestServiceDebugCmd proto.InternalMessageInfo

func (m *RequestServiceDebugCmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *RequestServiceDebugCmd) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetGroups() []int32 {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetUnit() []string {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetBeasts() []int32 {
	if m != nil {
		return m.Beasts
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetCommanders() [][]byte {
	if m != nil {
		return m.Commanders
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetApple() *ApplesServerin {
	if m != nil {
		return m.Apple
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetTem() map[string]int32 {
	if m != nil {
		return m.Tem
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetAddr() map[string]int32 {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetAddrEntry() map[string]*ApplesServerin {
	if m != nil {
		return m.AddrEntry
	}
	return nil
}

func (m *RequestServiceDebugCmd) GetAddrEntry2() map[string]*ApplesServerin {
	if m != nil {
		return m.AddrEntry2
	}
	return nil
}

type ApplesServerin struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Student              []int32  `protobuf:"varint,3,rep,packed,name=student,proto3" json:"student,omitempty"`
	Teacher              []string `protobuf:"bytes,4,rep,name=teacher,proto3" json:"teacher,omitempty"`
	Bb                   *Binary  `protobuf:"bytes,5,opt,name=bb,proto3" json:"bb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplesServerin) Reset()         { *m = ApplesServerin{} }
func (m *ApplesServerin) String() string { return proto.CompactTextString(m) }
func (*ApplesServerin) ProtoMessage()    {}
func (*ApplesServerin) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *ApplesServerin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplesServerin.Unmarshal(m, b)
}
func (m *ApplesServerin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplesServerin.Marshal(b, m, deterministic)
}
func (m *ApplesServerin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplesServerin.Merge(m, src)
}
func (m *ApplesServerin) XXX_Size() int {
	return xxx_messageInfo_ApplesServerin.Size(m)
}
func (m *ApplesServerin) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplesServerin.DiscardUnknown(m)
}

var xxx_messageInfo_ApplesServerin proto.InternalMessageInfo

func (m *ApplesServerin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApplesServerin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplesServerin) GetStudent() []int32 {
	if m != nil {
		return m.Student
	}
	return nil
}

func (m *ApplesServerin) GetTeacher() []string {
	if m != nil {
		return m.Teacher
	}
	return nil
}

func (m *ApplesServerin) GetBb() *Binary {
	if m != nil {
		return m.Bb
	}
	return nil
}

type Binary struct {
	Id                   []string        `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	Aa                   *ApplesServerin `protobuf:"bytes,2,opt,name=aa,proto3" json:"aa,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Binary) Reset()         { *m = Binary{} }
func (m *Binary) String() string { return proto.CompactTextString(m) }
func (*Binary) ProtoMessage()    {}
func (*Binary) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *Binary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binary.Unmarshal(m, b)
}
func (m *Binary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binary.Marshal(b, m, deterministic)
}
func (m *Binary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binary.Merge(m, src)
}
func (m *Binary) XXX_Size() int {
	return xxx_messageInfo_Binary.Size(m)
}
func (m *Binary) XXX_DiscardUnknown() {
	xxx_messageInfo_Binary.DiscardUnknown(m)
}

var xxx_messageInfo_Binary proto.InternalMessageInfo

func (m *Binary) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Binary) GetAa() *ApplesServerin {
	if m != nil {
		return m.Aa
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestServiceDebugCmd)(nil), "example.RequestServiceDebugCmd")
	proto.RegisterMapType((map[string]int32)(nil), "example.RequestServiceDebugCmd.AddrEntry")
	proto.RegisterMapType((map[string]*ApplesServerin)(nil), "example.RequestServiceDebugCmd.AddrEntry2Entry")
	proto.RegisterMapType((map[string]*ApplesServerin)(nil), "example.RequestServiceDebugCmd.AddrEntryEntry")
	proto.RegisterMapType((map[string]int32)(nil), "example.RequestServiceDebugCmd.TemEntry")
	proto.RegisterType((*ApplesServerin)(nil), "example.applesServerin")
	proto.RegisterType((*Binary)(nil), "example.Binary")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x65, 0x3b, 0x76, 0xea, 0x49, 0x49, 0xd1, 0x0a, 0x95, 0x55, 0x0f, 0x60, 0xe5, 0xc2,
	0x72, 0x68, 0x90, 0x82, 0x04, 0xa8, 0x12, 0x87, 0xf2, 0xe7, 0x86, 0x84, 0xb4, 0xfc, 0xb9, 0x8f,
	0xb3, 0xa3, 0x62, 0x35, 0xeb, 0x98, 0xf5, 0xba, 0x22, 0x1f, 0x81, 0x03, 0xdf, 0x19, 0xed, 0x6e,
	0xec, 0xa6, 0xa8, 0xa2, 0x41, 0xe2, 0xb6, 0x6f, 0x3c, 0xef, 0xa7, 0x79, 0x1a, 0x0f, 0xdc, 0xa3,
	0x1f, 0xa8, 0x9b, 0x15, 0xcd, 0x1b, 0xb3, 0xb6, 0x6b, 0x36, 0xde, 0xca, 0xd9, 0xaf, 0x0c, 0x8e,
	0x25, 0x7d, 0xef, 0xa8, 0xb5, 0x9f, 0xc8, 0x5c, 0x55, 0x4b, 0x7a, 0x47, 0x65, 0x77, 0xf1, 0x56,
	0x2b, 0x76, 0x1f, 0x92, 0xa5, 0x56, 0x3c, 0x2a, 0x22, 0x91, 0x4b, 0xf7, 0x64, 0x0f, 0x20, 0x6d,
	0xd0, 0xa0, 0xe6, 0x71, 0x11, 0x89, 0x43, 0x19, 0x04, 0x3b, 0x86, 0xec, 0xc2, 0xac, 0xbb, 0xa6,
	0xe5, 0x49, 0x91, 0x88, 0x54, 0x6e, 0x15, 0x63, 0x30, 0xea, 0xea, 0xca, 0xf2, 0x51, 0x91, 0x88,
	0x5c, 0xfa, 0xb7, 0xeb, 0x2d, 0x09, 0x5b, 0xdb, 0xf2, 0x34, 0xf4, 0x06, 0xc5, 0x1e, 0x01, 0x2c,
	0xd7, 0x5a, 0x63, 0xad, 0xc8, 0xb4, 0x3c, 0x2b, 0x12, 0x71, 0x28, 0x77, 0x2a, 0xec, 0x14, 0x52,
	0x6c, 0x9a, 0x15, 0xf1, 0x71, 0x11, 0x89, 0xc9, 0xe2, 0xe1, 0xbc, 0x8f, 0xe3, 0xab, 0xad, 0x1b,
	0x9d, 0x4c, 0x55, 0xcb, 0xd0, 0xc5, 0xce, 0x20, 0xb1, 0xa4, 0xf9, 0x41, 0x91, 0x88, 0xc9, 0x42,
	0x0c, 0xcd, 0xb7, 0x07, 0x9d, 0x7f, 0x26, 0xfd, 0xbe, 0xb6, 0x66, 0x23, 0x9d, 0x89, 0xbd, 0x86,
	0x11, 0x2a, 0x65, 0x78, 0xee, 0xcd, 0x4f, 0xef, 0x32, 0x9f, 0x2b, 0x65, 0x82, 0xdb, 0xdb, 0xd8,
	0x07, 0xc8, 0xb1, 0x2f, 0x71, 0xf0, 0x8c, 0xf9, 0xde, 0x8c, 0x00, 0xba, 0x06, 0xb0, 0x8f, 0x00,
	0x83, 0x58, 0xf0, 0x89, 0xc7, 0x3d, 0xdb, 0x1b, 0xb7, 0x08, 0xbc, 0x1d, 0xc4, 0xc9, 0x0b, 0x38,
	0xe8, 0xe3, 0xba, 0x05, 0x5f, 0xd2, 0xa6, 0x5f, 0xf0, 0x25, 0x6d, 0xdc, 0x82, 0xaf, 0x70, 0xd5,
	0x91, 0x5f, 0x70, 0x2a, 0x83, 0x38, 0x8b, 0x5f, 0x45, 0x27, 0x2f, 0x21, 0x1f, 0xb0, 0xff, 0x64,
	0xfc, 0x02, 0xd3, 0x9b, 0xf1, 0x6e, 0x71, 0x9f, 0xee, 0xba, 0xff, 0xb6, 0xdd, 0x6b, 0xec, 0x57,
	0x38, 0xfa, 0x23, 0xe6, 0x7f, 0xe1, 0xce, 0x7e, 0x46, 0x30, 0xbd, 0xf9, 0x95, 0x4d, 0x21, 0xae,
	0xc2, 0x19, 0xa4, 0x32, 0xae, 0x94, 0xfb, 0xaf, 0x6b, 0xd4, 0x01, 0x9a, 0x4b, 0xff, 0x66, 0x1c,
	0xc6, 0xad, 0xed, 0x14, 0xd5, 0x76, 0x7b, 0x04, 0xbd, 0x74, 0x5f, 0x2c, 0xe1, 0xf2, 0x1b, 0x99,
	0xed, 0x21, 0xf4, 0x92, 0x3d, 0x86, 0xb8, 0x2c, 0x79, 0xea, 0x47, 0x3b, 0x1a, 0x46, 0x7b, 0x53,
	0xd5, 0x68, 0x36, 0x32, 0x2e, 0xcb, 0xd9, 0x39, 0x64, 0x41, 0x0d, 0x23, 0x38, 0xbf, 0x1b, 0xe1,
	0x09, 0xc4, 0x88, 0x77, 0xa5, 0x8a, 0x11, 0xcb, 0xcc, 0x9f, 0xfb, 0xf3, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0xd9, 0x82, 0xca, 0xff, 0x03, 0x00, 0x00,
}
